// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// List all registered marketplaces with plugin counts.
	listMarketplaces: () => typedError<MarketplaceInfo[], CommandError>(__TAURI_INVOKE("list_marketplaces")),
	// List all plugins in a given marketplace.
	listPlugins: (marketplace: string) => typedError<PluginInfo[], CommandError>(__TAURI_INVOKE("list_plugins", { marketplace })),
	// List all available skills for a plugin, cross-referenced with installed state.
	listAvailableSkills: (marketplace: string, plugin: string, projectPath: string) => typedError<SkillInfo[], CommandError>(__TAURI_INVOKE("list_available_skills", { marketplace, plugin, projectPath })),
	/**
	 *  List all skills across every plugin in a marketplace, cross-referenced
	 *  with installed state.
	 * 
	 *  Bulk alternative to calling [`list_available_skills`] per plugin when no
	 *  plugin filter is active. Does one `load_installed` up front instead of
	 *  N (one per plugin), and returns a [`BulkSkillsResult`] whose `skipped`
	 *  field carries plugin-level errors (missing directory, malformed manifest)
	 *  so the frontend can surface a partial-listing warning. Per-skill errors
	 *  inside a working plugin (unreadable `SKILL.md`, bad frontmatter) are
	 *  always skipped silently with a `warn` — same behavior as the per-plugin
	 *  path.
	 */
	listAllSkillsForMarketplace: (marketplace: string, projectPath: string) => typedError<BulkSkillsResult, CommandError>(__TAURI_INVOKE("list_all_skills_for_marketplace", { marketplace, projectPath })),
	// Install specific skills from a plugin into a Kiro project.
	installSkills: (marketplace: string, plugin: string, skills: string[], force: boolean, projectPath: string) => typedError<InstallResult, CommandError>(__TAURI_INVOKE("install_skills", { marketplace, plugin, skills, force, projectPath })),
	// Get summary information about a Kiro project directory.
	getProjectInfo: (projectPath: string) => typedError<ProjectInfo, CommandError>(__TAURI_INVOKE("get_project_info", { projectPath })),
	// List all skills installed in a Kiro project, sorted by name.
	listInstalledSkills: (projectPath: string) => typedError<InstalledSkillInfo[], CommandError>(__TAURI_INVOKE("list_installed_skills", { projectPath })),
	// Remove an installed skill from a Kiro project.
	removeSkill: (name: string, projectPath: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_skill", { name, projectPath })),
	// Add a new marketplace source.
	addMarketplace: (source: string, protocol: 
// Clone via HTTPS (works through firewalls, uses credential helpers).
"https" | 
// Clone via SSH (uses SSH agent / keys).
"ssh" | null) => typedError<MarketplaceAddResult, CommandError>(__TAURI_INVOKE("add_marketplace", { source, protocol })),
	// Remove a registered marketplace and its cached data.
	removeMarketplace: (name: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_marketplace", { name })),
	// Update marketplace clone(s) from remote.
	updateMarketplace: (name: string | null) => typedError<UpdateResult, CommandError>(__TAURI_INVOKE("update_marketplace", { name })),
	// Load application settings.
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	// Save the list of scan root directories.
	saveScanRoots: (roots: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("save_scan_roots", { roots })),
	/**
	 *  Discover Kiro projects by scanning configured root directories.
	 * 
	 *  Scans each root up to 2 levels deep for directories containing `.kiro/`.
	 */
	discoverProjects: () => typedError<DiscoveredProject[], CommandError>(__TAURI_INVOKE("discover_projects")),
	// Set the active project and persist it.
	setActiveProject: (path: string) => typedError<ProjectInfo, CommandError>(__TAURI_INVOKE("set_active_project", { path })),
	// Load all Kiro CLI settings, merging the stored JSON with the registry defaults.
	getKiroSettings: () => typedError<SettingEntry[], CommandError>(__TAURI_INVOKE("get_kiro_settings")),
	/**
	 *  Update a single Kiro CLI setting by key and return the updated entry.
	 * 
	 *  All validation runs inside `apply_registered_setting` so the
	 *  "key in registry?" / "value type matches?" / "write" triple stays
	 *  atomic at the source of truth (kiro-market-core). Earlier this
	 *  command did the registry check here and the type check inline,
	 *  then handed the validated triple to the unchecked `set_nested`;
	 *  the new helper keeps the three steps inseparable so a future
	 *  caller can't drop one by accident.
	 */
	setKiroSetting: (key: string, value: SettingValue) => typedError<SettingEntry, CommandError>(__TAURI_INVOKE("set_kiro_setting", { key, value })),
	// Remove a single Kiro CLI setting by key, reverting it to its default.
	resetKiroSetting: (key: string) => typedError<null, CommandError>(__TAURI_INVOKE("reset_kiro_setting", { key })),
};

/* Types */
/**
 *  Response for [`list_all_skills_for_marketplace`]. `skipped` carries the
 *  plugins whose directory or manifest errored — the bulk path continues past
 *  such errors to preserve the partial listing, but the frontend needs to
 *  know which plugins were silently dropped so it can surface a warning.
 */
export type BulkSkillsResult = {
	skills: SkillInfo[],
	skipped: SkippedPlugin[],
};

/**
 *  Structured error response for Tauri commands.
 * 
 *  Provides a human-readable message alongside a machine-readable error type,
 *  enabling the frontend to make type-safe decisions about error handling and
 *  display appropriate messages without string parsing.
 */
export type CommandError = {
	message: string,
	error_type: ErrorType,
};

// A discovered Kiro project found during directory scanning.
export type DiscoveredProject = {
	// Absolute path to the project root.
	path: string,
	// Directory name (for display).
	name: string,
};

/**
 *  Machine-readable error classification for frontend conditional logic.
 * 
 *  Serialized as snake_case strings and exported to TypeScript via specta.
 */
export type ErrorType = "not_found" | "already_exists" | "validation" | "git_error" | "io_error" | "parse_error" | "unknown";

// A skill that failed to install, with the reason.
export type FailedSkill = {
	name: string,
	error: string,
};

// A marketplace that failed to update, with the reason.
export type FailedUpdate = {
	name: string,
	error: string,
};

/**
 *  Which transport protocol to use when cloning from a shorthand host
 *  reference (e.g. `owner/repo`).
 */
export type GitProtocol = 
// Clone via HTTPS (works through firewalls, uses credential helpers).
"https" | 
// Clone via SSH (uses SSH agent / keys).
"ssh";

// Result of an install operation across multiple skills.
export type InstallResult = {
	installed: string[],
	skipped: string[],
	failed: FailedSkill[],
};

// Information about a single installed skill.
export type InstalledSkillInfo = {
	name: string,
	marketplace: string,
	plugin: string,
	version: string | null,
	// ISO 8601 timestamp of when the skill was installed.
	installed_at: string,
};

// Result of adding a new marketplace.
export type MarketplaceAddResult = {
	name: string,
	plugins: PluginBasicInfo[],
	/**
	 *  How the marketplace contents are stored on disk. `Linked` means
	 *  changes to the source are reflected immediately; `Copied` (Windows
	 *  fallback when junctions fail) means the user must re-add to pick up
	 *  upstream edits. The frontend should surface this for `Copied` so
	 *  users aren't surprised that "live" updates do not work.
	 */
	storage: MarketplaceStorage,
};

// Summary information about a registered marketplace.
export type MarketplaceInfo = {
	name: string,
	source_type: SourceType,
	plugin_count: number,
	/**
	 *  If the marketplace manifest could not be read or parsed, this field
	 *  carries the error message so the frontend can show a warning.
	 */
	load_error: string | null,
};

// How a registered marketplace's contents are stored on disk.
export type MarketplaceStorage = 
// Cloned from a remote git repository.
"cloned" | 
/**
 *  Linked to a local directory (symlink on Unix, junction on Windows).
 *  Edits to the source are visible immediately.
 */
"linked" | 
/**
 *  Copied from a local directory (Windows fallback when junctions fail).
 *  Edits to the source require re-adding the marketplace.
 */
"copied";

// Basic information about a plugin within a marketplace.
export type PluginBasicInfo = {
	name: string,
	description: string | null,
};

// Summary information about a plugin within a marketplace.
export type PluginInfo = {
	name: string,
	description: string | null,
	skill_count: number,
	source_type: SourceType,
};

// Summary information about a Kiro project directory.
export type ProjectInfo = {
	path: string,
	kiro_initialized: boolean,
	installed_skill_count: number,
};

// Top-level category for a Kiro CLI setting.
export type SettingCategory = "telemetry" | "chat" | "knowledge" | "key_bindings" | "features" | "api" | "mcp" | "environment";

// A fully-resolved setting entry suitable for serialisation to a frontend.
export type SettingEntry = {
	// Dotted JSON key path.
	key: string,
	// Short human-readable label.
	label: string,
	// Longer description.
	description: string,
	// Typed category identifier.
	category: SettingCategory,
	// Human-readable category label.
	category_label: string,
	// Value type and type-specific metadata (discriminated union on the frontend).
	value_type: SettingValueInfo,
	/**
	 *  Default value. `None` when no default is known.
	 * 
	 *  Stored internally as a `serde_json::Value` to preserve round-trip
	 *  fidelity with `settings.json`. Emitted to specta as `SettingValue` so
	 *  the frontend sees a precise TypeScript union instead of an opaque
	 *  recursive JSON type.
	 */
	default_value: SettingValue | null,
	// Current value from the user's settings file. `None` means key absent (using default).
	current_value: SettingValue | null,
};

/**
 *  Every shape a Kiro CLI setting can hold — the frontend-safe subset of
 *  `serde_json::Value`. Declared as an untagged enum so the wire format is
 *  identical to raw JSON primitives, while giving specta a precise
 *  TypeScript union to emit. `Integer` precedes `Float` in the variant order
 *  so serde's untagged dispatch prefers `i64` for whole-number JSON literals
 *  and only falls through to `f64` for fractional inputs — preserving the
 *  integer/float distinction on round-trip through `settings.json`.
 */
export type SettingValue = boolean | number | string | string[];

/**
 *  Describes the value type and any type-specific metadata for a setting entry.
 * 
 *  Serialized as an internally-tagged enum so the frontend can use a
 *  discriminated union: `entry.value_type.kind === "bool"`.
 */
export type SettingValueInfo = { kind: "bool" } | { kind: "string" } | { kind: "number" } | { kind: "char" } | { kind: "string_array" } | { kind: "enum"; options: string[] };

// Persisted application settings.
export type Settings = {
	// Directories to scan for Kiro projects.
	scan_roots?: string[],
	// Last active project path (restored on launch).
	last_project?: string | null,
};

// Information about a single skill, including installation status.
export type SkillInfo = {
	name: string,
	description: string,
	plugin: string,
	marketplace: string,
	installed: boolean,
};

// A plugin that was excluded from a bulk skills listing, with the reason.
export type SkippedPlugin = {
	name: string,
	reason: string,
};

/**
 *  Source type classification for marketplaces and plugins.
 * 
 *  Serialized as snake_case strings. The TypeScript side receives a union
 *  type like `"github" | "git" | "local" | "relative" | "git_subdir"`.
 */
export type SourceType = "github" | "git" | "local" | "relative" | "git-subdir";

// Result of updating one or more marketplaces.
export type UpdateResult = {
	updated: string[],
	failed: FailedUpdate[],
	skipped: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

