// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// List all registered marketplaces with plugin counts.
	listMarketplaces: () => typedError<MarketplaceInfo[], CommandError>(__TAURI_INVOKE("list_marketplaces")),
	// List all plugins in a given marketplace.
	listPlugins: (marketplace: string) => typedError<PluginInfo[], CommandError>(__TAURI_INVOKE("list_plugins", { marketplace })),
	/**
	 *  List all available skills for a plugin, cross-referenced with installed state.
	 * 
	 *  Returns a [`PluginSkillsResult`] carrying both the happy-path skill list
	 *  and any per-skill read failures (unreadable `SKILL.md`, malformed
	 *  frontmatter) as [`PluginSkillsResult::skipped_skills`]. Previously these
	 *  per-skill failures vanished into `warn!` logs, leaving the frontend to
	 *  wonder why the count shrank; surfacing them structurally lets the UI
	 *  show "N skills failed to load" with a drill-down.
	 * 
	 *  The IPC-boundary [`MarketplaceName::new`] / [`PluginName::new`]
	 *  constructors plus [`validate_kiro_project_path`] gate the wrapper
	 *  before any service or filesystem access. Without these guards a
	 *  frontend-supplied `marketplace = "../etc/passwd"` would reach
	 *  [`MarketplaceService::marketplace_path`] (`cache::marketplace_path`)
	 *  via a bare path join and force an FS read at
	 *  `<registries_dir>/../etc/passwd` — the read-side analogue of the
	 *  install-side hardening from PR #94's I10. Validation runs *before*
	 *  [`make_service`] so rejection paths never touch `$HOME` / the cache
	 *  directory.
	 */
	listAvailableSkills: (marketplace: string, plugin: string, projectPath: string) => typedError<PluginSkillsResult, CommandError>(__TAURI_INVOKE("list_available_skills", { marketplace, plugin, projectPath })),
	/**
	 *  List all skills across every plugin in a marketplace, cross-referenced
	 *  with installed state.
	 * 
	 *  Bulk alternative to calling [`list_available_skills`] per plugin when no
	 *  plugin filter is active. The returned [`BulkSkillsResult::skipped`]
	 *  carries plugin-level errors (missing directory, malformed manifest,
	 *  remote source) so the frontend can surface a partial-listing warning.
	 * 
	 *  The IPC-boundary [`MarketplaceName::new`] plus
	 *  [`validate_kiro_project_path`] gate the wrapper before any service or
	 *  filesystem access — same defense-in-depth contract as
	 *  [`list_available_skills`].
	 */
	listAllSkillsForMarketplace: (marketplace: string, projectPath: string) => typedError<BulkSkillsResult, CommandError>(__TAURI_INVOKE("list_all_skills_for_marketplace", { marketplace, projectPath })),
	/**
	 *  Install specific skills from a plugin into a Kiro project.
	 * 
	 *  Returns the core [`InstallSkillsResult`] directly rather than through a
	 *  Tauri-local wrapper — the previous wrapper was a field-by-field copy
	 *  and risked drifting away from the core shape (e.g. losing the
	 *  structured `FailedSkill::kind` and `skipped_skills` fields).
	 *  Using the core type keeps the wire format lockstep with what the
	 *  service emits.
	 */
	installSkills: (marketplace: string, plugin: string, skills: string[], force: boolean, projectPath: string) => typedError<InstallSkillsResult, CommandError>(__TAURI_INVOKE("install_skills", { marketplace, plugin, skills, force, projectPath })),
	// Get summary information about a Kiro project directory.
	getProjectInfo: (projectPath: string) => typedError<ProjectInfo, CommandError>(__TAURI_INVOKE("get_project_info", { projectPath })),
	// List all skills installed in a Kiro project, sorted by name.
	listInstalledSkills: (projectPath: string) => typedError<InstalledSkillInfo[], CommandError>(__TAURI_INVOKE("list_installed_skills", { projectPath })),
	// Remove an installed skill from a Kiro project.
	removeSkill: (name: string, projectPath: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_skill", { name, projectPath })),
	// Add a new marketplace source.
	addMarketplace: (source: string, protocol: 
// Clone via HTTPS (works through firewalls, uses credential helpers).
"https" | 
// Clone via SSH (uses SSH agent / keys).
"ssh" | null) => typedError<MarketplaceAddResult, CommandError>(__TAURI_INVOKE("add_marketplace", { source, protocol })),
	// Remove a registered marketplace and its cached data.
	removeMarketplace: (name: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_marketplace", { name })),
	// Update marketplace clone(s) from remote.
	updateMarketplace: (name: string | null) => typedError<UpdateResult, CommandError>(__TAURI_INVOKE("update_marketplace", { name })),
	// Load application settings.
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	// Save the list of scan root directories.
	saveScanRoots: (roots: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("save_scan_roots", { roots })),
	/**
	 *  Discover Kiro projects by scanning configured root directories.
	 * 
	 *  Scans each root up to 2 levels deep for directories containing `.kiro/`.
	 */
	discoverProjects: () => typedError<DiscoveredProject[], CommandError>(__TAURI_INVOKE("discover_projects")),
	// Set the active project and persist it.
	setActiveProject: (path: string) => typedError<ProjectInfo, CommandError>(__TAURI_INVOKE("set_active_project", { path })),
	// Load all Kiro CLI settings, merging the stored JSON with the registry defaults.
	getKiroSettings: () => typedError<SettingEntry[], CommandError>(__TAURI_INVOKE("get_kiro_settings")),
	/**
	 *  Update a single Kiro CLI setting by key and return the updated entry.
	 * 
	 *  All validation runs inside `apply_registered_setting` so the
	 *  "key in registry?" / "value type matches?" / "write" triple stays
	 *  atomic at the source of truth (kiro-market-core). Earlier this
	 *  command did the registry check here and the type check inline,
	 *  then handed the validated triple to the unchecked `set_nested`;
	 *  the new helper keeps the three steps inseparable so a future
	 *  caller can't drop one by accident.
	 */
	setKiroSetting: (key: string, value: SettingValue) => typedError<SettingEntry, CommandError>(__TAURI_INVOKE("set_kiro_setting", { key, value })),
	// Remove a single Kiro CLI setting by key, reverting it to its default.
	resetKiroSetting: (key: string) => typedError<null, CommandError>(__TAURI_INVOKE("reset_kiro_setting", { key })),
	/**
	 *  Install every steering file declared by a plugin into the active
	 *  project's `.kiro/steering/` directory.
	 * 
	 *  The wrapper exists only to construct a [`MarketplaceService`] from
	 *  process globals and translate the FFI `force: bool` into an
	 *  [`InstallMode`]; the install itself runs in
	 *  [`install_plugin_steering_impl`] so it can be tested without a Tauri
	 *  runtime.
	 */
	installPluginSteering: (marketplace: string, plugin: string, force: boolean, projectPath: string) => typedError<InstallSteeringResult_Serialize, CommandError>(__TAURI_INVOKE("install_plugin_steering", { marketplace, plugin, force, projectPath })),
	/**
	 *  Install every agent declared by a plugin into the active project's
	 *  `.kiro/agents/` directory.
	 * 
	 *  The wrapper exists only to construct a [`MarketplaceService`] from
	 *  process globals and translate the FFI `force: bool` into an
	 *  [`InstallMode`]; the install itself runs in
	 *  [`install_plugin_agents_impl`] so it can be tested without a Tauri
	 *  runtime.
	 */
	installPluginAgents: (marketplace: string, plugin: string, force: boolean, acceptMcp: boolean, projectPath: string) => typedError<InstallAgentsResult_Serialize, CommandError>(__TAURI_INVOKE("install_plugin_agents", { marketplace, plugin, force, acceptMcp, projectPath })),
	/**
	 *  Install every skill, steering file, and agent declared by a plugin
	 *  into the active project's `.kiro/` tree in one call.
	 * 
	 *  The wrapper exists only to construct a [`MarketplaceService`] from
	 *  process globals and translate the FFI `force: bool` into an
	 *  [`InstallMode`]; the install itself runs in [`install_plugin_impl`]
	 *  so it can be tested without a Tauri runtime.
	 * 
	 *  `accept_mcp` is the per-call MCP opt-in gate (A-18). The Phase 1
	 *  frontend hardcodes `false` at the call site until a user-toggle UI
	 *  lands; the parameter is plumbed through so a later PR can flip it
	 *  without touching this signature.
	 */
	installPlugin: (marketplace: string, plugin: string, force: boolean, acceptMcp: boolean, projectPath: string) => typedError<InstallPluginResult_Serialize, CommandError>(__TAURI_INVOKE("install_plugin", { marketplace, plugin, force, acceptMcp, projectPath })),
	/**
	 *  List every installed plugin in the project, aggregated by
	 *  `(marketplace, plugin)` pair across the three tracking files.
	 * 
	 *  No `_impl` split (A-19): the body is inline in the wrapper because
	 *  the command consumes `KiroProject` only — there's no
	 *  `MarketplaceService` to thread through. Mirrors the existing
	 *  [`crate::commands::installed::list_installed_skills`] shape; tests
	 *  exercise the wrapper directly via `#[tokio::test]`.
	 */
	listInstalledPlugins: (projectPath: string) => typedError<InstalledPluginsView, CommandError>(__TAURI_INVOKE("list_installed_plugins", { projectPath })),
	/**
	 *  Remove every skill, steering file, and agent for a given
	 *  `(marketplace, plugin)` pair from the project, returning per-content
	 *  `removed: Vec<String>` lists plus per-content `failures` vecs.
	 * 
	 *  No `_impl` split (A-19): same rationale as
	 *  [`list_installed_plugins`] above — `KiroProject`-only read/write,
	 *  no service.
	 */
	removePlugin: (marketplace: string, plugin: string, projectPath: string) => typedError<RemovePluginResult, CommandError>(__TAURI_INVOKE("remove_plugin", { marketplace, plugin, projectPath })),
	/**
	 *  Scan installed plugins for available updates by comparing each
	 *  project tracking entry's recorded `version` and `source_hash`
	 *  against the corresponding plugin in the marketplace cache. Reads
	 *  from local cache only — callers that want fresh data run
	 *  `update_marketplaces` first.
	 * 
	 *  Returns a [`DetectUpdatesResult`] split into three vecs:
	 *  - `updates`: plugins with an available update (typed
	 *    `change_signal` distinguishes manifest version bump from
	 *    content drift without version bump).
	 *  - `failures`: plugins the scan couldn't check, with a typed
	 *    `kind: PluginUpdateFailureKind` for FE branching (Rule 42).
	 *  - `partial_load_warnings`: tracking files that failed to load
	 *    (corrupt JSON etc.) — the other tracking files still
	 *    contribute and the scan continues.
	 * 
	 *  Splits into [`detect_plugin_updates_impl`] per the
	 *  service-consuming-command convention so the body is testable
	 *  without a Tauri runtime.
	 * 
	 *  # Errors
	 * 
	 *  Returns `CommandError::Validation` on an invalid `project_path`.
	 *  Per-plugin scan failures land in
	 *  [`DetectUpdatesResult::failures`] (a typed entry, not an
	 *  `Err(CommandError)`) so a single bad plugin doesn't abort the
	 *  whole scan.
	 */
	detectPluginUpdates: (projectPath: string) => typedError<DetectUpdatesResult, CommandError>(__TAURI_INVOKE("detect_plugin_updates", { projectPath })),
};

/* Types */
/**
 *  Canonical content hash for installed artifacts.
 * 
 *  Stored on disk as the string `"blake3:" + 64 ASCII hex chars`. The
 *  type wraps a `String` with a private inner field so the only ways
 *  to construct one are (a) `BlakeHash::new` (validates the format),
 *  (b) the artifact-hash producers in this module ([`hash_artifact`]
 *  / [`hash_dir_tree`], which build the canonical form by
 *  construction), or (c) the `placeholder` constructor used during
 *  install scaffolding (and in test fixtures that don't care about the
 *  actual content).
 * 
 *  The `Deserialize` impl routes through `new`, so a tracking file
 *  containing `"source_hash": ""` (or any other malformed value) fails
 *  to load instead of being silently accepted as a sentinel.
 */
export type BlakeHash = string;

/**
 *  Result of a marketplace-wide skill listing. The bulk path continues
 *  past per-plugin errors (missing directory, malformed manifest) to
 *  preserve the partial listing; `skipped` records plugin-level drops
 *  and `skipped_skills` records per-skill drops inside otherwise-working
 *  plugins, so the frontend can show a warning rather than silently
 *  shrinking the count.
 */
export type BulkSkillsResult = {
	skills: SkillInfo[],
	skipped: SkippedPlugin[],
	skipped_skills: SkippedSkill[],
};

/**
 *  Structured error response for Tauri commands.
 * 
 *  Provides a human-readable message alongside a machine-readable error type,
 *  enabling the frontend to make type-safe decisions about error handling and
 *  display appropriate messages without string parsing.
 */
export type CommandError = {
	message: string,
	error_type: ErrorType,
};

/**
 *  Result of [`MarketplaceService::detect_plugin_updates`] — a scan over
 *  installed plugins. `updates` lists plugins with available updates;
 *  `failures` lists plugins the scan couldn't check (marketplace gone
 *  from cache, manifest malformed, hash computation failure). Plugins
 *  with no update available are absent from both vecs (the implicit
 *  "everything's fine" set).
 * 
 *  `partial_load_warnings` carries tracking-file load failures that
 *  happened before `installed_plugins()` returned — e.g. a corrupt
 *  `installed-skills.json` means the corresponding skills are missing
 *  from `plugins` and the warning is surfaced here so the caller can
 *  render a "partial state" banner.
 */
export type DetectUpdatesResult = {
	updates?: PluginUpdateInfo[],
	failures?: PluginUpdateFailure[],
	partial_load_warnings?: TrackingLoadWarning[],
};

// A discovered Kiro project found during directory scanning.
export type DiscoveredProject = {
	// Absolute path to the project root.
	path: string,
	// Directory name (for display).
	name: string,
};

/**
 *  Machine-readable error classification for frontend conditional logic.
 * 
 *  Serialized as snake_case strings and exported to TypeScript via specta.
 * 
 *  `Internal` is reserved for invariant violations the backend believes
 *  are unreachable (post-condition failures, registry/file-state desync,
 *  etc.). It is *not* the dustbin variant for unmapped errors — that role
 *  stays with `Unknown`, whose `From<CoreError>` arm logs a warning to
 *  signal "we forgot to map this." The frontend can grow special UX for
 *  `Internal` ("please file an issue") without it being noisy from
 *  unmapped-but-mundane errors.
 */
export type ErrorType = "not_found" | "already_exists" | "validation" | "git_error" | "io_error" | "parse_error" | "internal" | "unknown";

/**
 *  An agent that failed to install, with the typed error.
 * 
 *  `name` is `Some` once parsing has identified the agent; pre-parse
 *  failures use `source_path` as the fallback identifier. `error` is the
 *  typed [`AgentError`] so frontends can branch on cause without
 *  substring-matching the rendered message; a custom `Serialize` impl
 *  projects it to the chain string for the wire format.
 */
export type FailedAgent = FailedAgent_Serialize | FailedAgent_Deserialize;

/**
 *  An agent that failed to install, with the typed error.
 * 
 *  `name` is `Some` once parsing has identified the agent; pre-parse
 *  failures use `source_path` as the fallback identifier. `error` is the
 *  typed [`AgentError`] so frontends can branch on cause without
 *  substring-matching the rendered message; a custom `Serialize` impl
 *  projects it to the chain string for the wire format.
 */
export type FailedAgent_Deserialize = {
	name: string | null,
	source_path: string,
	/**
	 *  Typed error. `Serialize` renders it as a string via
	 *  [`crate::error::error_full_chain`] so the wire shape stays string;
	 *  in-process consumers can match on the typed variants directly.
	 */
	error: string,
};

/**
 *  An agent that failed to install, with the typed error.
 * 
 *  `name` is `Some` once parsing has identified the agent; pre-parse
 *  failures use `source_path` as the fallback identifier. `error` is the
 *  typed [`AgentError`] so frontends can branch on cause without
 *  substring-matching the rendered message; a custom `Serialize` impl
 *  projects it to the chain string for the wire format.
 */
export type FailedAgent_Serialize = {
	name: string | null,
	source_path: string,
	/**
	 *  Typed error. `Serialize` renders it as a string via
	 *  [`crate::error::error_full_chain`] so the wire shape stays string;
	 *  in-process consumers can match on the typed variants directly.
	 */
	error: string,
};

/**
 *  A skill that failed to install, with the reason.
 * 
 *  `error` is the human-readable Display (suitable for log lines or UI
 *  direct rendering); `kind` is the stable programmatic contract that
 *  frontends should `match` on when deciding how to render the failure.
 *  The two are deliberately redundant — `error` can rephrase freely over
 *  time, while `kind` stays stable.
 * 
 *  Fields are `pub(crate)` so external callers cannot desync the two —
 *  construction routes exclusively through [`Self::install_failed`] and
 *  [`Self::requested_but_not_found`], each of which derives `error` and
 *  `kind` together from a single source. Read access from outside the
 *  crate happens via the [`Self::name`] / [`Self::error`] / [`Self::kind`]
 *  accessors, and via the Serde/specta boundary (the generated
 *  TypeScript type still exposes all three fields, because Serde ignores
 *  Rust visibility). This mirrors the [`crate::service::browse::SkippedPlugin`]
 *  enforcement pattern so the two redundant-by-design types stay
 *  symmetric.
 */
export type FailedSkill = {
	name: string,
	error: string,
	kind: FailedSkillReason,
};

/**
 *  Why a skill install failed. Separates "we tried to install and it
 *  went wrong" ([`Self::InstallFailed`]) from "the caller named a skill
 *  that isn't in this plugin" ([`Self::RequestedButNotFound`]) so
 *  frontends can render a typo banner distinct from an install error
 *  without substring-matching `FailedSkill::error`.
 * 
 *  [`Self::InstallFailed`] is unit-shaped: the human-readable error
 *  message lives on [`FailedSkill::error`] and the typed `kind` here
 *  exists to tell the typo case apart from every other failure mode.
 *  Duplicating the error string into this variant would be redundant
 *  since `FailedSkill.error` is always populated.
 */
export type FailedSkillReason = 
/**
 *  The install was attempted (`SKILL.md` read and frontmatter
 *  parsed) but the filesystem copy / metadata write failed. See
 *  [`FailedSkill::error`] for the human-readable reason.
 */
{ kind: "install_failed" } | 
/**
 *  The caller's `Names(_)` filter included a name that no skill in
 *  the plugin's discovered list produced — typically a typo or a
 *  stale reference. The `plugin` field carries the plugin context
 *  so a flat UI list can attribute the miss.
 */
{ kind: "requested_but_not_found"; plugin: string };

/**
 *  Per-file failure entry in a steering install batch.
 * 
 *  In-process consumers see `error` as a typed [`SteeringError`] and can
 *  match on its variants. **Across the Tauri FFI** (and in the generated
 *  `bindings.ts`) `error` is a pre-rendered string carrying the full
 *  chain produced by [`crate::error::error_full_chain`] — TypeScript
 *  consumers should treat it as opaque diagnostic text, not as a
 *  structured value. Mirrors the precedent set by
 *  [`crate::service::FailedAgent`] / `serialize_agent_error`:
 *  [`SteeringError`] carries `io::Error` / `HashError` payloads that
 *  don't implement `Serialize`, and the serialized chain stays stable
 *  across variant additions.
 */
export type FailedSteeringFile = FailedSteeringFile_Serialize | FailedSteeringFile_Deserialize;

/**
 *  Per-file failure entry in a steering install batch.
 * 
 *  In-process consumers see `error` as a typed [`SteeringError`] and can
 *  match on its variants. **Across the Tauri FFI** (and in the generated
 *  `bindings.ts`) `error` is a pre-rendered string carrying the full
 *  chain produced by [`crate::error::error_full_chain`] — TypeScript
 *  consumers should treat it as opaque diagnostic text, not as a
 *  structured value. Mirrors the precedent set by
 *  [`crate::service::FailedAgent`] / `serialize_agent_error`:
 *  [`SteeringError`] carries `io::Error` / `HashError` payloads that
 *  don't implement `Serialize`, and the serialized chain stays stable
 *  across variant additions.
 */
export type FailedSteeringFile_Deserialize = {
	source: string,
	error: string,
};

/**
 *  Per-file failure entry in a steering install batch.
 * 
 *  In-process consumers see `error` as a typed [`SteeringError`] and can
 *  match on its variants. **Across the Tauri FFI** (and in the generated
 *  `bindings.ts`) `error` is a pre-rendered string carrying the full
 *  chain produced by [`crate::error::error_full_chain`] — TypeScript
 *  consumers should treat it as opaque diagnostic text, not as a
 *  structured value. Mirrors the precedent set by
 *  [`crate::service::FailedAgent`] / `serialize_agent_error`:
 *  [`SteeringError`] carries `io::Error` / `HashError` payloads that
 *  don't implement `Serialize`, and the serialized chain stays stable
 *  across variant additions.
 */
export type FailedSteeringFile_Serialize = {
	source: string,
	error: string,
};

// A marketplace that failed to update, with the reason.
export type FailedUpdate = {
	name: string,
	error: string,
};

/**
 *  Which transport protocol to use when cloning from a shorthand host
 *  reference (e.g. `owner/repo`).
 */
export type GitProtocol = 
// Clone via HTTPS (works through firewalls, uses credential helpers).
"https" | 
// Clone via SSH (uses SSH agent / keys).
"ssh";

/**
 *  Outcome of installing the agents from one plugin.
 * 
 *  Mirrors [`InstallSkillsResult`]: per-agent successes and failures are
 *  collected so a single broken agent never aborts the rest of the batch,
 *  and accumulated warnings always reach the caller even when some agents
 *  fail.
 */
export type InstallAgentsResult = InstallAgentsResult_Serialize | InstallAgentsResult_Deserialize;

/**
 *  Outcome of installing the agents from one plugin.
 * 
 *  Mirrors [`InstallSkillsResult`]: per-agent successes and failures are
 *  collected so a single broken agent never aborts the rest of the batch,
 *  and accumulated warnings always reach the caller even when some agents
 *  fail.
 */
export type InstallAgentsResult_Deserialize = {
	/**
	 *  Agent names successfully installed (both translated and native paths
	 *  populate this). Native idempotent reinstalls go to `skipped`.
	 */
	installed: string[],
	/**
	 *  Agent names that were already installed and left untouched.
	 *  Native paths populate this for idempotent reinstalls
	 *  (`kind == InstallOutcomeKind::Idempotent`).
	 */
	skipped: string[],
	// Agents whose install attempt failed (parse, validation, or fs error).
	failed: FailedAgent_Deserialize[],
	/**
	 *  Non-fatal issues (unmapped tools, skipped non-agent files,
	 *  MCP-gated agents).
	 */
	warnings: InstallWarning[],
	/**
	 *  Per-native-agent rich outcome (`kind`, hashes). Empty for
	 *  translated-only installs. Frontends that want the rich detail
	 *  consume this; legacy presenters keep using `installed: Vec<String>`.
	 * 
	 *  `serde` `default` is kept for round-trip parsing of legacy JSON
	 *  blobs that omit the field. `skip_serializing_if` was removed so
	 *  the type can flow through Tauri/Specta bindings — `tauri-specta`
	 *  2.0.0-rc.24's unified mode rejects conditional field omission.
	 *  Mirrors [`InstallSkillsResult`] and [`crate::steering::InstallSteeringResult`],
	 *  neither of which use `skip_serializing_if` either.
	 */
	installed_native?: InstalledNativeAgentOutcome[],
	/**
	 *  Per-plugin native companion bundle outcome. `None` for translated
	 *  plugins or for native plugins with zero companion files. See
	 *  [`Self::installed_native`] for why `skip_serializing_if` is absent.
	 */
	installed_companions?: InstalledNativeCompanionsOutcome | null,
};

/**
 *  Outcome of installing the agents from one plugin.
 * 
 *  Mirrors [`InstallSkillsResult`]: per-agent successes and failures are
 *  collected so a single broken agent never aborts the rest of the batch,
 *  and accumulated warnings always reach the caller even when some agents
 *  fail.
 */
export type InstallAgentsResult_Serialize = {
	/**
	 *  Agent names successfully installed (both translated and native paths
	 *  populate this). Native idempotent reinstalls go to `skipped`.
	 */
	installed: string[],
	/**
	 *  Agent names that were already installed and left untouched.
	 *  Native paths populate this for idempotent reinstalls
	 *  (`kind == InstallOutcomeKind::Idempotent`).
	 */
	skipped: string[],
	// Agents whose install attempt failed (parse, validation, or fs error).
	failed: FailedAgent_Serialize[],
	/**
	 *  Non-fatal issues (unmapped tools, skipped non-agent files,
	 *  MCP-gated agents).
	 */
	warnings: InstallWarning[],
	/**
	 *  Per-native-agent rich outcome (`kind`, hashes). Empty for
	 *  translated-only installs. Frontends that want the rich detail
	 *  consume this; legacy presenters keep using `installed: Vec<String>`.
	 * 
	 *  `serde` `default` is kept for round-trip parsing of legacy JSON
	 *  blobs that omit the field. `skip_serializing_if` was removed so
	 *  the type can flow through Tauri/Specta bindings — `tauri-specta`
	 *  2.0.0-rc.24's unified mode rejects conditional field omission.
	 *  Mirrors [`InstallSkillsResult`] and [`crate::steering::InstallSteeringResult`],
	 *  neither of which use `skip_serializing_if` either.
	 */
	installed_native: InstalledNativeAgentOutcome[],
	/**
	 *  Per-plugin native companion bundle outcome. `None` for translated
	 *  plugins or for native plugins with zero companion files. See
	 *  [`Self::installed_native`] for why `skip_serializing_if` is absent.
	 */
	installed_companions: InstalledNativeCompanionsOutcome | null,
};

/**
 *  What happened during one native install call. Three states are
 *  distinct variants rather than a `(was_idempotent: bool,
 *  forced_overwrite: bool)` pair so that the contradictory
 *  `(true, true)` state is unrepresentable by construction.
 */
export type InstallOutcomeKind = 
/**
 *  Verified no-op — `source_hash` matched the existing tracking
 *  entry's `source_hash`. No bytes were written.
 */
"idempotent" | 
// Clean first install — no prior tracking entry, no orphan on disk.
"installed" | 
/**
 *  Force-mode overwrote a tracked path (same plugin's prior content,
 *  another plugin's content via ownership transfer, or an orphan
 *  without tracking).
 */
"force_overwrote";

/**
 *  Aggregate result of [`MarketplaceService::install_plugin`] — the
 *  outcome of running every install path a plugin declares (skills,
 *  steering, agents) in one coordinated call.
 * 
 *  Sub-results are always populated. The underlying scan-path
 *  fallbacks (`agent_scan_paths_for_plugin` /
 *  `steering_scan_paths_for_plugin`) guarantee at least one attempt;
 *  `install_skills` returns a fully-formed default for empty input.
 *  Empty `installed` / `failed` vecs on a sub-result indicate "this
 *  content type was attempted with nothing to do" — distinct from a
 *  missing field.
 * 
 *  Phase 1.5 (A1+A4): the `marketplace` and `plugin` fields are typed
 *  newtypes (`MarketplaceName` / `PluginName`) — `serde(transparent)`
 *  in the wire format, so the JSON shape stays plain strings while the
 *  in-memory contract is parse-don't-validate. `Default` is intentionally
 *  not derived: the newtypes don't derive `Default`, and no consumer
 *  constructs an `InstallPluginResult::default()` — `install_plugin` is
 *  the only origin and always populates every field.
 */
export type InstallPluginResult = InstallPluginResult_Serialize | InstallPluginResult_Deserialize;

/**
 *  Aggregate result of [`MarketplaceService::install_plugin`] — the
 *  outcome of running every install path a plugin declares (skills,
 *  steering, agents) in one coordinated call.
 * 
 *  Sub-results are always populated. The underlying scan-path
 *  fallbacks (`agent_scan_paths_for_plugin` /
 *  `steering_scan_paths_for_plugin`) guarantee at least one attempt;
 *  `install_skills` returns a fully-formed default for empty input.
 *  Empty `installed` / `failed` vecs on a sub-result indicate "this
 *  content type was attempted with nothing to do" — distinct from a
 *  missing field.
 * 
 *  Phase 1.5 (A1+A4): the `marketplace` and `plugin` fields are typed
 *  newtypes (`MarketplaceName` / `PluginName`) — `serde(transparent)`
 *  in the wire format, so the JSON shape stays plain strings while the
 *  in-memory contract is parse-don't-validate. `Default` is intentionally
 *  not derived: the newtypes don't derive `Default`, and no consumer
 *  constructs an `InstallPluginResult::default()` — `install_plugin` is
 *  the only origin and always populates every field.
 */
export type InstallPluginResult_Deserialize = {
	marketplace: MarketplaceName,
	plugin: PluginName,
	version: string | null,
	skills: InstallSkillsResult,
	steering: InstallSteeringResult_Deserialize,
	agents: InstallAgentsResult_Deserialize,
};

/**
 *  Aggregate result of [`MarketplaceService::install_plugin`] — the
 *  outcome of running every install path a plugin declares (skills,
 *  steering, agents) in one coordinated call.
 * 
 *  Sub-results are always populated. The underlying scan-path
 *  fallbacks (`agent_scan_paths_for_plugin` /
 *  `steering_scan_paths_for_plugin`) guarantee at least one attempt;
 *  `install_skills` returns a fully-formed default for empty input.
 *  Empty `installed` / `failed` vecs on a sub-result indicate "this
 *  content type was attempted with nothing to do" — distinct from a
 *  missing field.
 * 
 *  Phase 1.5 (A1+A4): the `marketplace` and `plugin` fields are typed
 *  newtypes (`MarketplaceName` / `PluginName`) — `serde(transparent)`
 *  in the wire format, so the JSON shape stays plain strings while the
 *  in-memory contract is parse-don't-validate. `Default` is intentionally
 *  not derived: the newtypes don't derive `Default`, and no consumer
 *  constructs an `InstallPluginResult::default()` — `install_plugin` is
 *  the only origin and always populates every field.
 */
export type InstallPluginResult_Serialize = {
	marketplace: MarketplaceName,
	plugin: PluginName,
	version: string | null,
	skills: InstallSkillsResult,
	steering: InstallSteeringResult_Serialize,
	agents: InstallAgentsResult_Serialize,
};

// Outcome of installing a list of skill directories from one plugin.
export type InstallSkillsResult = {
	// Skill names successfully installed.
	installed: string[],
	// Skill names already installed and skipped (only when `force = false`).
	skipped: string[],
	/**
	 *  Skill names whose install attempt failed (install error, or — for
	 *  `Names(_)` filter — names requested but not found). Distinct from
	 *  [`Self::skipped_skills`], which tracks entries we couldn't even
	 *  read / parse before attempting to install them.
	 */
	failed: FailedSkill[],
	/**
	 *  Skill-source entries that could not be read or parsed, so no
	 *  install was attempted. Surfaces what previously vanished into
	 *  `warn!`-then-`continue`; mirrors
	 *  [`crate::service::browse::BulkSkillsResult::skipped_skills`].
	 */
	skipped_skills: SkippedSkill[],
};

// Aggregate result of `MarketplaceService::install_plugin_steering`.
export type InstallSteeringResult = InstallSteeringResult_Serialize | InstallSteeringResult_Deserialize;

// Aggregate result of `MarketplaceService::install_plugin_steering`.
export type InstallSteeringResult_Deserialize = {
	installed: InstalledSteeringOutcome[],
	failed: FailedSteeringFile_Deserialize[],
	warnings: SteeringWarning[],
};

// Aggregate result of `MarketplaceService::install_plugin_steering`.
export type InstallSteeringResult_Serialize = {
	installed: InstalledSteeringOutcome[],
	failed: FailedSteeringFile_Serialize[],
	warnings: SteeringWarning[],
};

/**
 *  Non-fatal issue produced during install. Surfaced in install results
 *  so the CLI / Tauri frontend can render them without blocking the install.
 * 
 *  Carries structured reason enums (not pre-rendered strings) so consumers
 *  can switch on them — the CLI formats for a human, the Tauri frontend
 *  can localize or map to its own UI states.
 * 
 *  Wire format: internally tagged on `kind` (`snake_case` discriminant) to
 *  match the workspace convention for FFI-crossing enums (`SteeringWarning`,
 *  `SkippedReason`, `FailedSkillReason`, `ParseFailure`). Enforced by the
 *  `ffi-enum-serde-tag` plan-lint gate.
 */
export type InstallWarning = 
/**
 *  A source-declared tool had no Kiro equivalent and was dropped.
 *  The emitted agent will inherit the full parent toolset for that slot.
 */
{ kind: "unmapped_tool"; agent: string; tool: string; reason: UnmappedReason } | 
// An agent file could not be parsed; it was skipped.
{ kind: "agent_parse_failed"; path: string; failure: ParseFailure } | 
/**
 *  An agent declares MCP servers but the install was not opted in
 *  to MCP. The agent was skipped — its prompt would otherwise
 *  install with a `mcpServers` block that runs subprocesses or
 *  opens network connections without the user's explicit consent.
 *  Listed transports help the user see the risk surface (e.g.
 *  `["stdio", "stdio", "http"]`) before they re-run with the
 *  `--accept-mcp` opt-in.
 */
{ kind: "mcp_servers_require_opt_in"; agent: string; transports: string[] };

/**
 *  In-memory outcome of one [`KiroProject::install_native_agent`] call.
 * 
 *  Carries enough detail for the service layer to render an install-summary
 *  row without re-reading tracking — name, the resolved destination JSON
 *  path, what kind of install happened, and both content hashes.
 */
export type InstalledNativeAgentOutcome = {
	name: string,
	json_path: string,
	kind: InstallOutcomeKind,
	source_hash: BlakeHash,
	installed_hash: BlakeHash,
};

/**
 *  In-memory outcome of one [`KiroProject::install_native_companions`] call.
 * 
 *  Plugin-scoped (companion bundles are owned per-plugin, not per-agent),
 *  so callers see one entry for the whole bundle rather than one per file.
 *  `files` is the absolute destination paths of every companion file
 *  installed for this plugin.
 */
export type InstalledNativeCompanionsOutcome = {
	plugin: string,
	files: string[],
	kind: InstallOutcomeKind,
	source_hash: BlakeHash,
	installed_hash: BlakeHash,
};

/**
 *  Aggregated view of a single installed plugin — the union of
 *  what's tracked across `installed-skills.json`,
 *  `installed-steering.json`, and `installed-agents.json` for a
 *  given `(marketplace, plugin)` pair.
 * 
 *  Returned by [`KiroProject::installed_plugins`]. The frontend
 *  renders one row per `InstalledPluginInfo`.
 * 
 *  `installed_version` is the version of the **most recent install**
 *  by `installed_at` timestamp — not a lexicographic max. See A-6
 *  in the plan amendments doc for why string-compare is wrong here.
 * 
 *  `earliest_install` and `latest_install` are RFC3339-formatted
 *  strings to match the FFI shape used by `InstalledSkillInfo`
 *  (specta's chrono feature isn't enabled in this crate).
 */
export type InstalledPluginInfo = {
	marketplace: MarketplaceName,
	plugin: PluginName,
	installed_version: string | null,
	skill_count: number,
	steering_count: number,
	agent_count: number,
	installed_skills: string[],
	installed_steering: string[],
	installed_agents: string[],
	// RFC3339-formatted timestamp.
	earliest_install: string,
	// RFC3339-formatted timestamp.
	latest_install: string,
};

/**
 *  Wire-format wrapper around [`Vec<InstalledPluginInfo>`] that also
 *  carries per-tracking-file load failures so the UI can render a
 *  partial state when one of the three `installed-*.json` files is
 *  corrupt or unreadable (I13).
 * 
 *  Rationale: previously, `installed_plugins()` failed the entire
 *  aggregator on any `?`-chain load failure, leaving the user with
 *  "zero installed plugins" even when two of three tracking files
 *  loaded cleanly. The view here surfaces what loaded AND what
 *  didn't, so the UI can show a "partial state — N tracking files
 *  failed to load" banner instead of a misleading empty list.
 */
export type InstalledPluginsView = {
	/**
	 *  Per-`(marketplace, plugin)` rows assembled from the tracking
	 *  files that loaded successfully. May be empty if every file
	 *  failed; the [`Self::partial_load_warnings`] vec then carries
	 *  the explanation.
	 */
	plugins: InstalledPluginInfo[],
	/**
	 *  One entry per `installed-*.json` whose load failed. The
	 *  corresponding content type's contributions are missing from
	 *  `plugins`. Empty on a clean state.
	 * 
	 *  `serde(default)` is kept for legacy-JSON tolerance.
	 *  `skip_serializing_if` is intentionally absent — `tauri-specta`
	 *  2.0.0-rc.24 unified mode rejects it (see A-25 in plan
	 *  amendments). Empty Vec serializes as `[]` rather than being
	 *  omitted, matching `InstallSkillsResult.failed` etc.
	 */
	partial_load_warnings?: TrackingLoadWarning[],
};

// Information about a single installed skill.
export type InstalledSkillInfo = {
	name: string,
	marketplace: string,
	plugin: string,
	version: string | null,
	// ISO 8601 timestamp of when the skill was installed.
	installed_at: string,
};

/**
 *  Per-call outcome of `KiroProject::install_steering_file`.
 * 
 *  The `kind` field uses the workspace-shared [`InstallOutcomeKind`] so
 *  presenters can match exhaustively over the same 3-variant enum used
 *  by `InstalledNativeAgentOutcome` and `InstalledNativeCompanionsOutcome`.
 */
export type InstalledSteeringOutcome = {
	source: string,
	destination: string,
	kind: InstallOutcomeKind,
	source_hash: BlakeHash,
	installed_hash: BlakeHash,
};

// Result of adding a new marketplace.
export type MarketplaceAddResult = {
	name: string,
	plugins: PluginBasicInfo[],
	/**
	 *  How the marketplace contents are stored on disk. `Linked` means
	 *  changes to the source are reflected immediately; `Copied` (Windows
	 *  fallback when junctions fail) means the user must re-add to pick up
	 *  upstream edits. The frontend should surface this for `Copied` so
	 *  users aren't surprised that "live" updates do not work.
	 */
	storage: MarketplaceStorage,
};

// Summary information about a registered marketplace.
export type MarketplaceInfo = {
	name: string,
	source_type: SourceType,
	plugin_count: number,
	/**
	 *  If the marketplace manifest could not be read or parsed, this field
	 *  carries the error message so the frontend can show a warning.
	 */
	load_error: string | null,
};

/**
 *  Validated marketplace name. Routes through [`validate_name`] at construction
 *  — non-empty, no NUL/control bytes, no path-traversal, no Windows-reserved
 *  names. The `serde(transparent)` representation keeps the JSON wire format
 *  byte-identical to a plain string; `Deserialize` is routed through `new` so
 *  `serde_json::from_slice` rejects malformed names at parse time.
 * 
 *  Deliberately does NOT derive `Default` — `MarketplaceName::default()` would
 *  return `MarketplaceName(String::new())` which `validate_name` rejects.
 *  Matches the existing `RelativePath` / `AgentName` / `GitRef` precedent.
 * 
 *  `Ord`/`PartialOrd` are derived for use as `BTreeMap` keys in
 *  `installed_plugins`'s aggregator (see `project.rs`). Lexicographic ordering
 *  on the inner string is well-defined and semantically equivalent to
 *  `String`'s ordering. Deviates from `RelativePath` / `AgentName` / `GitRef`
 *  (which don't derive `Ord`) because none of those types are used as map keys
 *  today.
 */
export type MarketplaceName = string;

// How a registered marketplace's contents are stored on disk.
export type MarketplaceStorage = 
// Cloned from a remote git repository.
"cloned" | 
/**
 *  Linked to a local directory (symlink on Unix, junction on Windows).
 *  Edits to the source are visible immediately.
 */
"linked" | 
/**
 *  Copied from a local directory (Windows fallback when junctions fail).
 *  Edits to the source require re-adding the marketplace.
 */
"copied";

/**
 *  Structured reason a source agent file could not be parsed.
 * 
 *  Replaces the pre-rendered `reason: String` that earlier versions carried
 *  on `AgentError` and `InstallWarning`. Callers switch on variants
 *  (e.g. to demote `MissingFrontmatter` to debug logs for README-style
 *  files) rather than substring-matching on error text — which would
 *  silently break the moment a message is reworded.
 * 
 *  Wire format: internally tagged on `kind` (`snake_case` discriminant)
 *  to match the workspace convention for FFI-crossing enums
 *  (`SteeringWarning`, `SkippedReason`, `FailedSkillReason`, …). All
 *  payload-bearing variants use struct-style fields rather than tuple
 *  fields because internal tagging requires named fields. Enforced by
 *  the `ffi-enum-serde-tag` plan-lint gate.
 */
export type ParseFailure = 
/**
 *  No opening `---` fence. Usually a README or other prose file
 *  accidentally scanned from the agents directory. Service layer
 *  demotes this to a debug log.
 */
{ kind: "missing_frontmatter" } | 
/**
 *  Opening fence present but no closing fence — a broken file that
 *  the user probably wants to hear about.
 */
{ kind: "unclosed_frontmatter" } | 
// YAML parser rejected the frontmatter block.
{ kind: "invalid_yaml"; reason: string } | 
// Frontmatter parsed but lacks the required `name` key.
{ kind: "missing_name" } | 
/**
 *  Frontmatter `name` failed validation (unsafe for use as a filename).
 *  `reason` carries the validator's human-readable explanation.
 */
{ kind: "invalid_name"; reason: string } | 
/**
 *  File read failed (permission denied, not found during racy delete,
 *  etc.). `reason` carries the rendered I/O error message.
 */
{ kind: "io_error"; reason: string } | 
/**
 *  The translated parser (`parse_agent_file`) was called with a file
 *  whose detected dialect belongs on a different install code path.
 *  Currently fires only for [`AgentDialect::Native`]: native agents are
 *  installed via validate-and-copy through `parse_native_kiro_agent_file`,
 *  not through `parse_agent_file`. The service routes by dialect
 *  upstream, so this branch is a defensive sanity check rather than a
 *  normal failure mode.
 * 
 *  Distinct from [`ParseFailure::IoError`] so callers branching on
 *  "should I retry the I/O?" don't misclassify a routing bug as a
 *  transient I/O failure.
 */
{ kind: "unsupported_dialect" };

// Basic information about a plugin within a marketplace.
export type PluginBasicInfo = {
	name: string,
	description: string | null,
};

// Summary information about a plugin within a marketplace.
export type PluginInfo = {
	name: string,
	description: string | null,
	skill_count: SkillCount,
	source_type: SourceType,
};

/**
 *  Validated plugin name. Same shape as [`MarketplaceName`]; see that type's
 *  documentation for the construction, serde, and Ord-derive contracts.
 */
export type PluginName = string;

/**
 *  Result of [`MarketplaceService::list_skills_for_plugin`]. Mirrors
 *  [`BulkSkillsResult`] for the single-plugin case so per-skill read
 *  failures surface structurally rather than only via `warn!` logs.
 */
export type PluginSkillsResult = {
	skills: SkillInfo[],
	skipped_skills: SkippedSkill[],
};

/**
 *  A plugin the update scan couldn't check.
 * 
 *  `kind` is the stable programmatic discriminant frontends should
 *  `match` on (per CLAUDE.md Rule 42: match error types, not error
 *  strings). `reason` is the rendered error chain via
 *  [`crate::error::error_full_chain`] per the FFI rule — suitable for
 *  log lines or fallback UI rendering, but never for branching logic.
 */
export type PluginUpdateFailure = {
	marketplace: MarketplaceName,
	plugin: PluginName,
	kind: PluginUpdateFailureKind,
	reason: string,
};

/**
 *  Why an update-detection scan couldn't check a plugin. Tagged enum
 *  for FFI per the `ffi-enum-serde-tag` plan-lint gate (PR #91):
 *  `#[serde(tag = "kind", rename_all = "snake_case")]` produces
 *  `{ "kind": "manifest_unreadable" }` in JSON, which `tauri-specta`
 *  emits as a discriminated TS union.
 * 
 *  Closes original-review I4: `PluginUpdateFailure` was opaque
 *  (substring matching `reason` to differentiate failure types
 *  violated CLAUDE.md Rule 42). The classifier
 *  [`PluginUpdateFailureKind::from_error`] is exhaustive per the
 *  CLAUDE.md classifier rule — a new error variant either matches
 *  here explicitly or routes through `Other` after a written-down
 *  rationale.
 */
export type PluginUpdateFailureKind = 
/**
 *  Marketplace cache directory missing or plugin removed from
 *  the marketplace's manifest.
 */
{ kind: "marketplace_unavailable" } | 
/**
 *  `plugin.json` missing in the marketplace cache (typically the
 *  plugin was deleted from upstream and the cache hasn't been
 *  refreshed). Also covers symlink-refused per the C5 defense.
 */
{ kind: "manifest_unreadable" } | 
/**
 *  `plugin.json` exists but failed to parse (malformed JSON,
 *  missing required fields, etc.).
 */
{ kind: "manifest_invalid" } | 
/**
 *  Hash recomputation against an installed file failed (file
 *  missing in the cache, permission denied, etc.).
 */
{ kind: "hash_failed" } | 
/**
 *  Catch-all for unanticipated failure shapes. Surfacing this
 *  rather than panicking lets the FE render a generic "scan
 *  failed" badge while the typed variants drive specific
 *  remediation. Each new error class deliberately routed here
 *  should also be considered for promotion to a typed variant.
 */
{ kind: "other" };

/**
 *  A single plugin with an update available.
 * 
 *  The `change_signal` discriminates between manifest-version change
 *  and content-drift-without-version-bump.
 */
export type PluginUpdateInfo = {
	marketplace: MarketplaceName,
	plugin: PluginName,
	/**
	 *  `None` means the project's tracking file lacked a `version`
	 *  field at install time (a legacy install pre-Stage-1, before
	 *  the version field was added to the tracking schema). Cases
	 *  where the tracking file itself failed to load are surfaced via
	 *  [`DetectUpdatesResult::partial_load_warnings`], NOT via
	 *  `Some(None)` here.
	 */
	installed_version: string | null,
	/**
	 *  `None` means the marketplace plugin manifest exists but lacks
	 *  a `version` field. After NC1's `ManifestState` 3-state
	 *  split, cases where the manifest is missing or unreadable
	 *  (symlinked, `NotFound`) surface as a [`PluginUpdateFailure`] —
	 *  they no longer collapse into `Some(None)` here. So
	 *  `available_version: None` is now an unambiguous "marketplace
	 *  says no version" signal.
	 */
	available_version: string | null,
	change_signal: UpdateChangeSignal,
};

// Summary information about a Kiro project directory.
export type ProjectInfo = {
	path: string,
	kiro_initialized: boolean,
	installed_skill_count: number,
};

/**
 *  A string that has been validated as a safe relative path.
 * 
 *  Construction goes through [`RelativePath::new`], which applies
 *  [`validate_relative_path`] — so holding a `RelativePath` is a static
 *  guarantee that the inner string is non-empty, contains no `..`
 *  components, no NUL bytes, and is not an absolute path.
 * 
 *  The newtype replaces a plain `String` in the manifest data model
 *  (`PluginSource::RelativePath`, `StructuredSource::GitSubdir.path`) so
 *  downstream code never needs to re-validate. `Deserialize` calls
 *  `new` internally, so `serde_json::from_slice::<Marketplace>(…)`
 *  rejects traversal at parse time.
 */
export type RelativePath = string;

/**
 *  Per-content-type sub-result for [`RemovePluginResult`]. Mirrors
 *  the install-side [`crate::service::InstallAgentsResult`] shape.
 *  `removed` is a flat vec of translated agent names + native agent
 *  names. Native companion file paths are NOT itemized (P2a-3
 *  decision α) — the `native_companions` cascade step succeeds with
 *  no per-file entries. If the FE later wants per-companion
 *  granularity, that's an additive field change.
 */
export type RemoveAgentsResult = {
	removed?: string[],
	failures?: RemoveItemFailure[],
};

/**
 *  One failure during a per-content-type removal step. The discriminator
 *  (which content type) is the parent type — no `content_type: String`
 *  field needed (it's expressed structurally via the parent's field
 *  name in [`RemovePluginResult`]).
 */
export type RemoveItemFailure = {
	/**
	 *  The skill/agent name or steering rel-path rendered via
	 *  [`std::path::Path::display`].
	 */
	item: string,
	/**
	 *  Rendered error chain via [`crate::error::error_full_chain`] —
	 *  wire format per CLAUDE.md FFI rule.
	 */
	error: string,
};

/**
 *  Result of [`KiroProject::remove_plugin`] — per-content-type
 *  sub-results, symmetric with [`crate::service::InstallPluginResult`].
 *  Native companions fold into [`RemoveAgentsResult`] (matches the
 *  install-side asymmetry where native companions are agent-side
 *  artifacts).
 * 
 *  No `marketplace` / `plugin` echo fields — caller already passed
 *  those args to `remove_plugin`. (Different from
 *  [`crate::service::InstallPluginResult`] which gained `marketplace`
 *  in Phase 1.5 A4 because that type lives in lists where
 *  self-identification is needed.)
 */
export type RemovePluginResult = {
	skills: RemoveSkillsResult,
	steering: RemoveSteeringResult,
	agents: RemoveAgentsResult,
};

/**
 *  Per-content-type sub-result for [`RemovePluginResult`]. Mirrors
 *  the install-side [`InstallSkillsResult`] shape.
 */
export type RemoveSkillsResult = {
	removed?: string[],
	failures?: RemoveItemFailure[],
};

/**
 *  Per-content-type sub-result for [`RemovePluginResult`]. Mirrors
 *  the install-side `InstallSteeringResult` shape.
 */
export type RemoveSteeringResult = {
	removed?: string[],
	failures?: RemoveItemFailure[],
};

// Top-level category for a Kiro CLI setting.
export type SettingCategory = "telemetry" | "chat" | "knowledge" | "key_bindings" | "features" | "api" | "mcp" | "environment";

// A fully-resolved setting entry suitable for serialisation to a frontend.
export type SettingEntry = {
	// Dotted JSON key path.
	key: string,
	// Short human-readable label.
	label: string,
	// Longer description.
	description: string,
	// Typed category identifier.
	category: SettingCategory,
	// Human-readable category label.
	category_label: string,
	// Value type and type-specific metadata (discriminated union on the frontend).
	value_type: SettingValueInfo,
	/**
	 *  Default value. `None` when no default is known.
	 * 
	 *  Stored internally as a `serde_json::Value` to preserve round-trip
	 *  fidelity with `settings.json`. Emitted to specta as `SettingValue` so
	 *  the frontend sees a precise TypeScript union instead of an opaque
	 *  recursive JSON type.
	 */
	default_value: SettingValue | null,
	// Current value from the user's settings file. `None` means key absent (using default).
	current_value: SettingValue | null,
};

/**
 *  Every shape a Kiro CLI setting can hold — the frontend-safe subset of
 *  `serde_json::Value`. Declared as an untagged enum so the wire format is
 *  identical to raw JSON primitives, while giving specta a precise
 *  TypeScript union to emit. `Integer` precedes `Float` in the variant order
 *  so serde's untagged dispatch prefers `i64` for whole-number JSON literals
 *  and only falls through to `f64` for fractional inputs — preserving the
 *  integer/float distinction on round-trip through `settings.json`.
 */
export type SettingValue = boolean | number | string | string[];

/**
 *  Describes the value type and any type-specific metadata for a setting entry.
 * 
 *  Serialized as an internally-tagged enum so the frontend can use a
 *  discriminated union: `entry.value_type.kind === "bool"`.
 */
export type SettingValueInfo = { kind: "bool" } | { kind: "string" } | { kind: "number" } | { kind: "char" } | { kind: "string_array" } | { kind: "enum"; options: string[] };

// Persisted application settings.
export type Settings = {
	// Directories to scan for Kiro projects.
	scan_roots?: string[],
	// Last active project path (restored on launch).
	last_project?: string | null,
};

/**
 *  Result of [`MarketplaceService::count_skills_for_plugin`].
 *  Distinguishes the three cases the frontend must render differently:
 *  a known count, a remote plugin (not locally countable), and a local
 *  plugin whose directory or manifest could not be loaded. Replaces the
 *  prior `usize` that collapsed failures into a silent `0`.
 */
export type SkillCount = 
/**
 *  The plugin directory was readable; `count` is the number of
 *  discovered skill directories (including the legitimate zero case).
 */
{ state: "known"; count: number } | 
/**
 *  Plugin source is remote (GitHub / git URL). Skills cannot be
 *  enumerated without cloning, which the listing path never does.
 *  Distinct from `ManifestFailed { reason: RemoteSourceNotLocal }`:
 *  here we know the plugin is remote by construction and never
 *  attempt the local resolution.
 */
{ state: "remote_not_counted" } | 
/**
 *  The plugin is local but something about its directory or
 *  `plugin.json` prevented a skill count.
 * 
 *  `SkippedReason` is reused as the error payload to share the
 *  [`SkippedReason::from_plugin_error`] classifier. Reachable from
 *  this path:
 * 
 *  From the `MarketplaceService::resolve_local_plugin_dir` pre-check:
 *  - [`SkippedReason::DirectoryMissing`] — `plugin_dir` not found.
 *  - [`SkippedReason::NotADirectory`] — `plugin_dir` is a file.
 *  - [`SkippedReason::SymlinkRefused`] — `plugin_dir` is a symlink.
 *  - [`SkippedReason::DirectoryUnreadable`] — stat failed for any
 *    other reason (permission denied, transient I/O, etc.).
 * 
 *  From the `plugin.json` load:
 *  - [`SkippedReason::InvalidManifest`] — `plugin.json` malformed.
 *  - [`SkippedReason::ManifestReadFailed`] — `plugin.json` read
 *    failed after a successful stat.
 * 
 *  [`SkippedReason::NoSkills`] is not produced anywhere in this
 *  path; [`SkippedReason::RemoteSourceNotLocal`] is pre-empted by
 *  [`Self::RemoteNotCounted`] before resolution is attempted.
 *  Frontends typed against `SkippedReason` will not get
 *  compile-time narrowing for those two — accepted because
 *  consolidating the projection is more valuable than a narrower
 *  wire type.
 */
{ state: "manifest_failed"; reason: SkippedReason };

/**
 *  Information about a single skill, cross-referenced with the target
 *  project's installed set.
 * 
 *  `installed` is a point-in-time snapshot — the project's
 *  `.kiro/installed.json` at the moment the listing was built. Callers
 *  that want a live view must re-query.
 */
export type SkillInfo = {
	name: string,
	description: string,
	plugin: string,
	marketplace: string,
	installed: boolean,
};

/**
 *  A plugin that was excluded from a bulk listing. Carries both a
 *  human-readable `reason` (the error's rendered Display, suitable for
 *  direct UI rendering or log lines) and a structured `kind` that
 *  frontends match on for variant-specific affordances (e.g. a "clone"
 *  button for [`SkippedReason::RemoteSourceNotLocal`]). The two are
 *  deliberately redundant: `reason` is free-form text that may rephrase
 *  over time, while `kind` is the stable programmatic contract.
 * 
 *  Fields are `pub(crate)` so external callers cannot desync the two
 *  — construction routes exclusively through
 *  [`SkippedPlugin::from_plugin_error`], which derives both from a
 *  single source error. Read access from outside the crate happens via
 *  the Serde/specta boundary (the generated TypeScript type still
 *  exposes all three fields, because Serde ignores Rust visibility).
 */
export type SkippedPlugin = {
	name: string,
	reason: string,
	kind: SkippedReason,
};

/**
 *  Why a plugin was excluded from a bulk listing. Structured counterpart
 *  to [`SkippedPlugin::reason`] so frontends can match on the cause
 *  (rendering variant-specific UI like a "clone" button for
 *  [`Self::RemoteSourceNotLocal`]) instead of substring-matching a
 *  rendered error message.
 * 
 *  Mirrors the plugin-level subset of [`PluginError`] — exactly the
 *  variants the bulk path folds into `skipped` rather than propagating.
 *  Kept as a distinct type because [`PluginError`] is a Display-oriented
 *  error carrying non-`Clone` `io::Error` chains, while `SkippedReason`
 *  is `Serialize + specta::Type` data that crosses the FFI boundary.
 *  Translating one to the other is the service layer's job, performed in
 *  a single place so the projection stays consistent with the error
 *  classifier.
 */
export type SkippedReason = { kind: "directory_missing"; path: string } | { kind: "not_a_directory"; path: string } | { kind: "symlink_refused"; path: string } | { kind: "directory_unreadable"; path: string; reason: string } | { kind: "invalid_manifest"; path: string; reason: string } | { kind: "manifest_read_failed"; path: string; reason: string } | { kind: "remote_source_not_local"; plugin: string; source: StructuredSource } | 
/**
 *  The plugin exists and its manifest is well-formed, but it
 *  declares no skills. Defensive classification — today no producer
 *  in the bulk/listing path returns [`PluginError::NoSkills`], but
 *  folding it into `skipped` means a future caller that DOES surface
 *  it can't accidentally abort the bulk listing. The plugin name
 *  lives on the wrapping [`SkippedPlugin`]; this variant carries
 *  only `path` for UI remediation (the directory the user might
 *  populate).
 */
{ kind: "no_skills"; path: string };

/**
 *  A skill that was excluded from a listing because its `SKILL.md` or
 *  frontmatter could not be read. Surfaces what previously vanished
 *  into `warn!`-then-`continue` so the frontend can render "N skills
 *  failed to load" with a drill-down rather than silently shrinking the
 *  listed count.
 */
export type SkippedSkill = {
	/**
	 *  Name of the plugin this skill was being enumerated under. The
	 *  bulk path [`MarketplaceService::list_all_skills`] accumulates
	 *  `SkippedSkill`s across every plugin in a marketplace, so without
	 *  this attribution the frontend would have no way to group "N
	 *  skills failed to load in plugin X" — making the structured
	 *  surface strictly less useful than the per-plugin `warn!` it
	 *  replaced. Per-plugin callers already have the plugin context
	 *  but carry it anyway so both code paths produce identical shapes.
	 */
	plugin: string,
	/**
	 *  Directory name of the skill as a best-effort label. Not a
	 *  guarantee the skill *would* have had this name — the frontmatter
	 *  `name` is authoritative, and parsing it is precisely what failed.
	 *  `None` when `Path::file_name()` cannot extract a component
	 *  (empty path, root, or a path terminating in `..`). Encoded as
	 *  `Option<String>` rather than a sentinel empty string so the
	 *  frontend's type system forces the "no label available" branch
	 *  to be handled explicitly — specta renders it as `string | null`.
	 */
	name_hint: string | null,
	// Path to the `SKILL.md` file that could not be consumed.
	path: string,
	reason: SkippedSkillReason,
};

/**
 *  Why an individual skill was excluded from a listing. Both variants
 *  describe a working plugin with a single broken skill file — a
 *  plugin-level failure surfaces as [`SkippedPlugin`] / [`SkippedReason`]
 *  instead.
 */
export type SkippedSkillReason = 
/**
 *  Reading `SKILL.md` failed (permission denied, I/O error, invalid
 *  UTF-8, etc.). `reason` carries the underlying error's Display.
 */
{ kind: "read_failed"; reason: string } | 
/**
 *  `SKILL.md` read successfully but the frontmatter could not be
 *  parsed (missing fences, malformed YAML, missing `name`, etc.).
 */
{ kind: "frontmatter_invalid"; reason: string };

/**
 *  Source type classification for marketplaces and plugins.
 * 
 *  Serialized as snake_case strings. The TypeScript side receives a union
 *  type like `"github" | "git" | "local" | "relative" | "git_subdir"`.
 */
export type SourceType = "github" | "git" | "local" | "relative" | "git-subdir";

/**
 *  Non-fatal issues raised during steering discovery. Surface
 *  actionable signals only — by-design exclusions (README-style files,
 *  symlinks refused for security) stay as `tracing::debug!` so the
 *  CLI doesn't spam users with normal product behaviour.
 * 
 *  Per the original S3-2 amendment this enum was scoped wider; the
 *  `Skipped` variant was retired during PR-64 review when it became
 *  clear surfacing every README would teach users to ignore warnings,
 *  and that symlink/junction refusals are by-design security behaviour
 *  rather than actionable feedback for plugin authors.
 * 
 *  The `reason: String` payloads on both variants are pre-rendered;
 *  upgrading them to typed payloads (`ValidationError` / `io::Error`)
 *  is tracked at
 *  <https://github.com/dwalleck/kiro-control-center/issues/66>.
 */
export type SteeringWarning = 
/**
 *  A steering scan path declared in the manifest failed validation
 *  (path-traversal, absolute, embedded NUL, non-utf-8 component).
 *  `path` carries the raw manifest value — almost always a typo
 *  worth surfacing to the plugin author. The validation rejection
 *  is also logged at `tracing::warn!` for operators.
 */
{ kind: "scan_path_invalid"; path: string; reason: string } | 
/**
 *  A steering scan directory exists but couldn't be read
 *  (permission denied, I/O error). Distinct from `NotFound` —
 *  missing directories are a silent no-op since plugins commonly
 *  declare `./steering/` without authoring any files. This variant
 *  fires only for system-level failures the user can act on.
 */
{ kind: "scan_dir_unreadable"; path: string; reason: string };

/**
 *  Provider-specific structured source descriptor, internally tagged on `"source"`.
 * 
 *  Carries `specta::Type` because `SkippedReason::RemoteSourceNotLocal`
 *  embeds a `StructuredSource` payload in the browse service's
 *  frontend-bound response. The `RelativePath` inside `GitSubdir.path`
 *  already carries specta via its own newtype, so the whole tree exports
 *  cleanly without further changes.
 */
export type StructuredSource = 
// A GitHub repository.
{ source: "github"; repo: string; ref: string | null; sha: string | null } | 
// A plain Git URL.
{ source: "url"; url: string; ref: string | null; sha: string | null } | 
// A subdirectory within a Git repository.
{ source: "git-subdir"; url: string; 
/**
 *  The subdir is typed as [`RelativePath`] so traversal cannot even
 *  exist in-memory — `RelativePath::new` is the only way in.
 */
path: RelativePath; ref: string | null; sha: string | null };

/**
 *  Per-tracking-file load failure surfaced by
 *  [`KiroProject::installed_plugins`] (I13).
 */
export type TrackingLoadWarning = {
	/**
	 *  Filename relative to `.kiro/`: `"installed-skills.json"` /
	 *  `"installed-steering.json"` / `"installed-agents.json"`. Just
	 *  the basename — the absolute path leaks layout information the
	 *  frontend doesn't need.
	 */
	tracking_file: string,
	/**
	 *  Rendered error chain via [`crate::error::error_full_chain`] —
	 *  wire format per CLAUDE.md "in any wire-format `reason`/`error:
	 *  String` field that crosses the FFI, use `error_full_chain(&err)`".
	 */
	error: string,
};

export type UnmappedReason = 
// Claude `PascalCase` name with no Kiro equivalent (e.g. `NotebookEdit`).
"NoKiroEquivalent" | 
/**
 *  Copilot bare name (e.g. `codebase`, `findTestFiles`) — internal Copilot
 *  concept with no reliable Kiro mapping.
 */
"BareCopilotName";

/**
 *  Why an update is being surfaced. Tagged enum for FFI per the
 *  `ffi-enum-serde-tag` plan-lint gate (PR #91): `#[serde(tag = "kind",
 *  rename_all = "snake_case")]` produces `{ "kind": "version_bumped" }`
 *  in JSON, which `tauri-specta` emits as a discriminated TS union.
 */
export type UpdateChangeSignal = 
/**
 *  Manifest version string differs (with or without content hash diff).
 *  Designed for FE rendering as "Update v1.0 → v1.1".
 */
{ kind: "version_bumped" } | 
/**
 *  Manifest version unchanged but at least one source-hash diff
 *  detected. Designed for FE rendering as "Content updated since install".
 */
{ kind: "content_changed" };

// Result of updating one or more marketplaces.
export type UpdateResult = {
	updated: string[],
	failed: FailedUpdate[],
	skipped: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

