// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	// List all registered marketplaces with plugin counts.
	listMarketplaces: () => typedError<MarketplaceInfo[], CommandError>(__TAURI_INVOKE("list_marketplaces")),
	// List all plugins in a given marketplace.
	listPlugins: (marketplace: string) => typedError<PluginInfo[], CommandError>(__TAURI_INVOKE("list_plugins", { marketplace })),
	/**
	 *  List all available skills for a plugin, cross-referenced with installed state.
	 * 
	 *  Returns a [`PluginSkillsResult`] carrying both the happy-path skill list
	 *  and any per-skill read failures (unreadable `SKILL.md`, malformed
	 *  frontmatter) as [`PluginSkillsResult::skipped_skills`]. Previously these
	 *  per-skill failures vanished into `warn!` logs, leaving the frontend to
	 *  wonder why the count shrank; surfacing them structurally lets the UI
	 *  show "N skills failed to load" with a drill-down.
	 */
	listAvailableSkills: (marketplace: string, plugin: string, projectPath: string) => typedError<PluginSkillsResult, CommandError>(__TAURI_INVOKE("list_available_skills", { marketplace, plugin, projectPath })),
	/**
	 *  List all skills across every plugin in a marketplace, cross-referenced
	 *  with installed state.
	 * 
	 *  Bulk alternative to calling [`list_available_skills`] per plugin when no
	 *  plugin filter is active. The returned [`BulkSkillsResult::skipped`]
	 *  carries plugin-level errors (missing directory, malformed manifest,
	 *  remote source) so the frontend can surface a partial-listing warning.
	 */
	listAllSkillsForMarketplace: (marketplace: string, projectPath: string) => typedError<BulkSkillsResult, CommandError>(__TAURI_INVOKE("list_all_skills_for_marketplace", { marketplace, projectPath })),
	/**
	 *  Install specific skills from a plugin into a Kiro project.
	 * 
	 *  Returns the core [`InstallSkillsResult`] directly rather than through a
	 *  Tauri-local wrapper — the previous wrapper was a field-by-field copy
	 *  and risked drifting away from the core shape (e.g. losing the
	 *  `FailedSkill::kind` and `skipped_skills` fields introduced in #30).
	 *  Using the core type keeps the wire format lockstep with what the
	 *  service emits.
	 */
	installSkills: (marketplace: string, plugin: string, skills: string[], force: boolean, projectPath: string) => typedError<InstallSkillsResult, CommandError>(__TAURI_INVOKE("install_skills", { marketplace, plugin, skills, force, projectPath })),
	// Get summary information about a Kiro project directory.
	getProjectInfo: (projectPath: string) => typedError<ProjectInfo, CommandError>(__TAURI_INVOKE("get_project_info", { projectPath })),
	// List all skills installed in a Kiro project, sorted by name.
	listInstalledSkills: (projectPath: string) => typedError<InstalledSkillInfo[], CommandError>(__TAURI_INVOKE("list_installed_skills", { projectPath })),
	// Remove an installed skill from a Kiro project.
	removeSkill: (name: string, projectPath: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_skill", { name, projectPath })),
	// Add a new marketplace source.
	addMarketplace: (source: string, protocol: 
// Clone via HTTPS (works through firewalls, uses credential helpers).
"https" | 
// Clone via SSH (uses SSH agent / keys).
"ssh" | null) => typedError<MarketplaceAddResult, CommandError>(__TAURI_INVOKE("add_marketplace", { source, protocol })),
	// Remove a registered marketplace and its cached data.
	removeMarketplace: (name: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_marketplace", { name })),
	// Update marketplace clone(s) from remote.
	updateMarketplace: (name: string | null) => typedError<UpdateResult, CommandError>(__TAURI_INVOKE("update_marketplace", { name })),
	// Load application settings.
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	// Save the list of scan root directories.
	saveScanRoots: (roots: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("save_scan_roots", { roots })),
	/**
	 *  Discover Kiro projects by scanning configured root directories.
	 * 
	 *  Scans each root up to 2 levels deep for directories containing `.kiro/`.
	 */
	discoverProjects: () => typedError<DiscoveredProject[], CommandError>(__TAURI_INVOKE("discover_projects")),
	// Set the active project and persist it.
	setActiveProject: (path: string) => typedError<ProjectInfo, CommandError>(__TAURI_INVOKE("set_active_project", { path })),
	// Load all Kiro CLI settings, merging the stored JSON with the registry defaults.
	getKiroSettings: () => typedError<SettingEntry[], CommandError>(__TAURI_INVOKE("get_kiro_settings")),
	/**
	 *  Update a single Kiro CLI setting by key and return the updated entry.
	 * 
	 *  All validation runs inside `apply_registered_setting` so the
	 *  "key in registry?" / "value type matches?" / "write" triple stays
	 *  atomic at the source of truth (kiro-market-core). Earlier this
	 *  command did the registry check here and the type check inline,
	 *  then handed the validated triple to the unchecked `set_nested`;
	 *  the new helper keeps the three steps inseparable so a future
	 *  caller can't drop one by accident.
	 */
	setKiroSetting: (key: string, value: SettingValue) => typedError<SettingEntry, CommandError>(__TAURI_INVOKE("set_kiro_setting", { key, value })),
	// Remove a single Kiro CLI setting by key, reverting it to its default.
	resetKiroSetting: (key: string) => typedError<null, CommandError>(__TAURI_INVOKE("reset_kiro_setting", { key })),
};

/* Types */
/**
 *  Result of a marketplace-wide skill listing. The bulk path continues
 *  past per-plugin errors (missing directory, malformed manifest) to
 *  preserve the partial listing; `skipped` records plugin-level drops
 *  and `skipped_skills` records per-skill drops inside otherwise-working
 *  plugins, so the frontend can show a warning rather than silently
 *  shrinking the count.
 */
export type BulkSkillsResult = {
	skills: SkillInfo[],
	skipped: SkippedPlugin[],
	skipped_skills: SkippedSkill[],
};

/**
 *  Structured error response for Tauri commands.
 * 
 *  Provides a human-readable message alongside a machine-readable error type,
 *  enabling the frontend to make type-safe decisions about error handling and
 *  display appropriate messages without string parsing.
 */
export type CommandError = {
	message: string,
	error_type: ErrorType,
};

// A discovered Kiro project found during directory scanning.
export type DiscoveredProject = {
	// Absolute path to the project root.
	path: string,
	// Directory name (for display).
	name: string,
};

/**
 *  Machine-readable error classification for frontend conditional logic.
 * 
 *  Serialized as snake_case strings and exported to TypeScript via specta.
 */
export type ErrorType = "not_found" | "already_exists" | "validation" | "git_error" | "io_error" | "parse_error" | "unknown";

/**
 *  A skill that failed to install, with the reason.
 * 
 *  `error` is the human-readable Display (suitable for log lines or UI
 *  direct rendering); `kind` is the stable programmatic contract that
 *  frontends should `match` on when deciding how to render the failure.
 *  The two are deliberately redundant — `error` can rephrase freely over
 *  time, while `kind` stays stable.
 * 
 *  Fields are `pub(crate)` so external callers cannot desync the two —
 *  construction routes exclusively through [`Self::install_failed`] and
 *  [`Self::requested_but_not_found`], each of which derives `error` and
 *  `kind` together from a single source. Read access from outside the
 *  crate happens via the [`Self::name`] / [`Self::error`] / [`Self::kind`]
 *  accessors, and via the Serde/specta boundary (the generated
 *  TypeScript type still exposes all three fields, because Serde ignores
 *  Rust visibility). This mirrors the [`crate::service::browse::SkippedPlugin`]
 *  enforcement pattern so the two redundant-by-design types stay
 *  symmetric.
 */
export type FailedSkill = {
	name: string,
	error: string,
	kind: FailedSkillReason,
};

/**
 *  Why a skill install failed. Separates "we tried to install and it
 *  went wrong" ([`Self::InstallFailed`]) from "the caller named a skill
 *  that isn't in this plugin" ([`Self::RequestedButNotFound`]) so
 *  frontends can render a typo banner distinct from an install error
 *  without substring-matching `FailedSkill::error`.
 * 
 *  [`Self::InstallFailed`] is unit-shaped: the human-readable error
 *  message lives on [`FailedSkill::error`] and the typed `kind` here
 *  exists to tell the typo case apart from every other failure mode.
 *  Duplicating the error string into this variant would be redundant
 *  since `FailedSkill.error` is always populated.
 */
export type FailedSkillReason = 
/**
 *  The install was attempted (`SKILL.md` read and frontmatter
 *  parsed) but the filesystem copy / metadata write failed. See
 *  [`FailedSkill::error`] for the human-readable reason.
 */
{ kind: "install_failed" } | 
/**
 *  The caller's `Names(_)` filter included a name that no skill in
 *  the plugin's discovered list produced — typically a typo or a
 *  stale reference. The `plugin` field carries the plugin context
 *  so a flat UI list can attribute the miss.
 */
{ kind: "requested_but_not_found"; plugin: string };

// A marketplace that failed to update, with the reason.
export type FailedUpdate = {
	name: string,
	error: string,
};

/**
 *  Which transport protocol to use when cloning from a shorthand host
 *  reference (e.g. `owner/repo`).
 */
export type GitProtocol = 
// Clone via HTTPS (works through firewalls, uses credential helpers).
"https" | 
// Clone via SSH (uses SSH agent / keys).
"ssh";

// Outcome of installing a list of skill directories from one plugin.
export type InstallSkillsResult = {
	// Skill names successfully installed.
	installed: string[],
	// Skill names already installed and skipped (only when `force = false`).
	skipped: string[],
	/**
	 *  Skill names whose install attempt failed (install error, or — for
	 *  `Names(_)` filter — names requested but not found). Distinct from
	 *  [`Self::skipped_skills`], which tracks entries we couldn't even
	 *  read / parse before attempting to install them.
	 */
	failed: FailedSkill[],
	/**
	 *  Skill-source entries that could not be read or parsed, so no
	 *  install was attempted. Surfaces what previously vanished into
	 *  `warn!`-then-`continue`; mirrors
	 *  [`crate::service::browse::BulkSkillsResult::skipped_skills`].
	 */
	skipped_skills: SkippedSkill[],
};

// Information about a single installed skill.
export type InstalledSkillInfo = {
	name: string,
	marketplace: string,
	plugin: string,
	version: string | null,
	// ISO 8601 timestamp of when the skill was installed.
	installed_at: string,
};

// Result of adding a new marketplace.
export type MarketplaceAddResult = {
	name: string,
	plugins: PluginBasicInfo[],
	/**
	 *  How the marketplace contents are stored on disk. `Linked` means
	 *  changes to the source are reflected immediately; `Copied` (Windows
	 *  fallback when junctions fail) means the user must re-add to pick up
	 *  upstream edits. The frontend should surface this for `Copied` so
	 *  users aren't surprised that "live" updates do not work.
	 */
	storage: MarketplaceStorage,
};

// Summary information about a registered marketplace.
export type MarketplaceInfo = {
	name: string,
	source_type: SourceType,
	plugin_count: number,
	/**
	 *  If the marketplace manifest could not be read or parsed, this field
	 *  carries the error message so the frontend can show a warning.
	 */
	load_error: string | null,
};

// How a registered marketplace's contents are stored on disk.
export type MarketplaceStorage = 
// Cloned from a remote git repository.
"cloned" | 
/**
 *  Linked to a local directory (symlink on Unix, junction on Windows).
 *  Edits to the source are visible immediately.
 */
"linked" | 
/**
 *  Copied from a local directory (Windows fallback when junctions fail).
 *  Edits to the source require re-adding the marketplace.
 */
"copied";

// Basic information about a plugin within a marketplace.
export type PluginBasicInfo = {
	name: string,
	description: string | null,
};

// Summary information about a plugin within a marketplace.
export type PluginInfo = {
	name: string,
	description: string | null,
	skill_count: number,
	source_type: SourceType,
};

/**
 *  Result of [`MarketplaceService::list_skills_for_plugin`]. Mirrors
 *  [`BulkSkillsResult`] for the single-plugin case so per-skill read
 *  failures surface structurally rather than only via `warn!` logs.
 */
export type PluginSkillsResult = {
	skills: SkillInfo[],
	skipped_skills: SkippedSkill[],
};

// Summary information about a Kiro project directory.
export type ProjectInfo = {
	path: string,
	kiro_initialized: boolean,
	installed_skill_count: number,
};

/**
 *  A string that has been validated as a safe relative path.
 * 
 *  Construction goes through [`RelativePath::new`], which applies
 *  [`validate_relative_path`] — so holding a `RelativePath` is a static
 *  guarantee that the inner string is non-empty, contains no `..`
 *  components, no NUL bytes, and is not an absolute path.
 * 
 *  The newtype replaces a plain `String` in the manifest data model
 *  (`PluginSource::RelativePath`, `StructuredSource::GitSubdir.path`) so
 *  downstream code never needs to re-validate. `Deserialize` calls
 *  `new` internally, so `serde_json::from_slice::<Marketplace>(…)`
 *  rejects traversal at parse time.
 */
export type RelativePath = string;

// Top-level category for a Kiro CLI setting.
export type SettingCategory = "telemetry" | "chat" | "knowledge" | "key_bindings" | "features" | "api" | "mcp" | "environment";

// A fully-resolved setting entry suitable for serialisation to a frontend.
export type SettingEntry = {
	// Dotted JSON key path.
	key: string,
	// Short human-readable label.
	label: string,
	// Longer description.
	description: string,
	// Typed category identifier.
	category: SettingCategory,
	// Human-readable category label.
	category_label: string,
	// Value type and type-specific metadata (discriminated union on the frontend).
	value_type: SettingValueInfo,
	/**
	 *  Default value. `None` when no default is known.
	 * 
	 *  Stored internally as a `serde_json::Value` to preserve round-trip
	 *  fidelity with `settings.json`. Emitted to specta as `SettingValue` so
	 *  the frontend sees a precise TypeScript union instead of an opaque
	 *  recursive JSON type.
	 */
	default_value: SettingValue | null,
	// Current value from the user's settings file. `None` means key absent (using default).
	current_value: SettingValue | null,
};

/**
 *  Every shape a Kiro CLI setting can hold — the frontend-safe subset of
 *  `serde_json::Value`. Declared as an untagged enum so the wire format is
 *  identical to raw JSON primitives, while giving specta a precise
 *  TypeScript union to emit. `Integer` precedes `Float` in the variant order
 *  so serde's untagged dispatch prefers `i64` for whole-number JSON literals
 *  and only falls through to `f64` for fractional inputs — preserving the
 *  integer/float distinction on round-trip through `settings.json`.
 */
export type SettingValue = boolean | number | string | string[];

/**
 *  Describes the value type and any type-specific metadata for a setting entry.
 * 
 *  Serialized as an internally-tagged enum so the frontend can use a
 *  discriminated union: `entry.value_type.kind === "bool"`.
 */
export type SettingValueInfo = { kind: "bool" } | { kind: "string" } | { kind: "number" } | { kind: "char" } | { kind: "string_array" } | { kind: "enum"; options: string[] };

// Persisted application settings.
export type Settings = {
	// Directories to scan for Kiro projects.
	scan_roots?: string[],
	// Last active project path (restored on launch).
	last_project?: string | null,
};

/**
 *  Information about a single skill, cross-referenced with the target
 *  project's installed set.
 * 
 *  `installed` is a point-in-time snapshot — the project's
 *  `.kiro/installed.json` at the moment the listing was built. Callers
 *  that want a live view must re-query.
 */
export type SkillInfo = {
	name: string,
	description: string,
	plugin: string,
	marketplace: string,
	installed: boolean,
};

/**
 *  A plugin that was excluded from a bulk listing. Carries both a
 *  human-readable `reason` (the error's rendered Display, suitable for
 *  direct UI rendering or log lines) and a structured `kind` that
 *  frontends match on for variant-specific affordances (e.g. a "clone"
 *  button for [`SkippedReason::RemoteSourceNotLocal`]). The two are
 *  deliberately redundant: `reason` is free-form text that may rephrase
 *  over time, while `kind` is the stable programmatic contract.
 * 
 *  Fields are `pub(crate)` so external callers cannot desync the two
 *  — construction routes exclusively through
 *  [`SkippedPlugin::from_plugin_error`], which derives both from a
 *  single source error. Read access from outside the crate happens via
 *  the Serde/specta boundary (the generated TypeScript type still
 *  exposes all three fields, because Serde ignores Rust visibility).
 */
export type SkippedPlugin = {
	name: string,
	reason: string,
	kind: SkippedReason,
};

/**
 *  Why a plugin was excluded from a bulk listing. Structured counterpart
 *  to [`SkippedPlugin::reason`] so frontends can match on the cause
 *  (rendering variant-specific UI like a "clone" button for
 *  [`Self::RemoteSourceNotLocal`]) instead of substring-matching a
 *  rendered error message.
 * 
 *  Mirrors the plugin-level subset of [`PluginError`] — exactly the
 *  variants the bulk path folds into `skipped` rather than propagating.
 *  Kept as a distinct type because [`PluginError`] is a Display-oriented
 *  error carrying non-`Clone` `io::Error` chains, while `SkippedReason`
 *  is `Serialize + specta::Type` data that crosses the FFI boundary.
 *  Translating one to the other is the service layer's job, performed in
 *  a single place so the projection stays consistent with the error
 *  classifier.
 */
export type SkippedReason = { kind: "directory_missing"; path: string } | { kind: "not_a_directory"; path: string } | { kind: "symlink_refused"; path: string } | { kind: "directory_unreadable"; path: string; reason: string } | { kind: "invalid_manifest"; path: string; reason: string } | { kind: "manifest_read_failed"; path: string; reason: string } | { kind: "remote_source_not_local"; plugin: string; source: StructuredSource } | 
/**
 *  The plugin exists and its manifest is well-formed, but it
 *  declares no skills. Defensive classification — today no producer
 *  in the bulk/listing path returns [`PluginError::NoSkills`], but
 *  folding it into `skipped` means a future caller that DOES surface
 *  it can't accidentally abort the bulk listing. The plugin name
 *  lives on the wrapping [`SkippedPlugin`]; this variant carries
 *  only `path` for UI remediation (the directory the user might
 *  populate).
 */
{ kind: "no_skills"; path: string };

/**
 *  A skill that was excluded from a listing because its `SKILL.md` or
 *  frontmatter could not be read. Surfaces what previously vanished
 *  into `warn!`-then-`continue` so the frontend can render "N skills
 *  failed to load" with a drill-down rather than silently shrinking the
 *  listed count.
 */
export type SkippedSkill = {
	/**
	 *  Name of the plugin this skill was being enumerated under. The
	 *  bulk path [`MarketplaceService::list_all_skills`] accumulates
	 *  `SkippedSkill`s across every plugin in a marketplace, so without
	 *  this attribution the frontend would have no way to group "N
	 *  skills failed to load in plugin X" — making the structured
	 *  surface strictly less useful than the per-plugin `warn!` it
	 *  replaced. Per-plugin callers already have the plugin context
	 *  but carry it anyway so both code paths produce identical shapes.
	 */
	plugin: string,
	/**
	 *  Directory name of the skill as a best-effort label. Not a
	 *  guarantee the skill *would* have had this name — the frontmatter
	 *  `name` is authoritative, and parsing it is precisely what failed.
	 *  `None` when `Path::file_name()` cannot extract a component
	 *  (empty path, root, or a path terminating in `..`). Encoded as
	 *  `Option<String>` rather than a sentinel empty string so the
	 *  frontend's type system forces the "no label available" branch
	 *  to be handled explicitly — specta renders it as `string | null`.
	 */
	name_hint: string | null,
	// Path to the `SKILL.md` file that could not be consumed.
	path: string,
	reason: SkippedSkillReason,
};

/**
 *  Why an individual skill was excluded from a listing. Both variants
 *  describe a working plugin with a single broken skill file — a
 *  plugin-level failure surfaces as [`SkippedPlugin`] / [`SkippedReason`]
 *  instead.
 */
export type SkippedSkillReason = 
/**
 *  Reading `SKILL.md` failed (permission denied, I/O error, invalid
 *  UTF-8, etc.). `reason` carries the underlying error's Display.
 */
{ kind: "read_failed"; reason: string } | 
/**
 *  `SKILL.md` read successfully but the frontmatter could not be
 *  parsed (missing fences, malformed YAML, missing `name`, etc.).
 */
{ kind: "frontmatter_invalid"; reason: string };

/**
 *  Source type classification for marketplaces and plugins.
 * 
 *  Serialized as snake_case strings. The TypeScript side receives a union
 *  type like `"github" | "git" | "local" | "relative" | "git_subdir"`.
 */
export type SourceType = "github" | "git" | "local" | "relative" | "git-subdir";

/**
 *  Provider-specific structured source descriptor, internally tagged on `"source"`.
 * 
 *  Carries `specta::Type` because `SkippedReason::RemoteSourceNotLocal`
 *  embeds a `StructuredSource` payload in the browse service's
 *  frontend-bound response. The `RelativePath` inside `GitSubdir.path`
 *  already carries specta via its own newtype, so the whole tree exports
 *  cleanly without further changes.
 */
export type StructuredSource = 
// A GitHub repository.
{ source: "github"; repo: string; ref: string | null; sha: string | null } | 
// A plain Git URL.
{ source: "url"; url: string; ref: string | null; sha: string | null } | 
// A subdirectory within a Git repository.
{ source: "git-subdir"; url: string; 
/**
 *  The subdir is typed as [`RelativePath`] so traversal cannot even
 *  exist in-memory — `RelativePath::new` is the only way in.
 */
path: RelativePath; ref: string | null; sha: string | null };

// Result of updating one or more marketplaces.
export type UpdateResult = {
	updated: string[],
	failed: FailedUpdate[],
	skipped: string[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

